kind: pipeline
type: docker
name: default

steps:
  # maven打包
  - name: build
    image: maven:3-jdk-8
    volumes:
      - name: maven_local_repo
        path: /root/.m2
    commands:
      - mvn clean -Ptest package -DskipTests=true -Dmaven.javadoc.skip=true

  # docker镜像推送
#  - name: docker
#    image: plugins/docker
#    settings:
#      username:
#        from_secret: docker_user
#      password:
#        from_secret: docker_pwd
#      mirror: https://wm9kcxms.mirror.aliyuncs.com
#      repo: registry.cn-hangzhou.aliyuncs.com/hbhb/drone-ci
#      registry: registry.cn-hangzhou.aliyuncs.com
#      tags: latest
#      dockerfile: ./Dockerfile

  # ssh远程执行脚本
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 112.13.201.108
      port: 2022
      username: root
      password: Qaz2@wsx
#      key:
#        from_secret: ssh_key
      command_timeout: 3m
      script_stop: false
      script:
        - docker-compose ps

  # 钉钉通知
  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token: d0edc79758683c62866f3303a0aa1c8239485d30d85e07204153f4890f323f6a
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
    when:
      status: [failure, success]

volumes:
  - name: maven_local_repo
    host:
      path: /app/data/maven_local_repo
