kind: pipeline
type: docker
name: default

steps:
  # maven打包
  - name: build
    image: maven:3-jdk-8
    volumes:
      - name: maven_local_repo
        path: /root/.m2
    commands:
      - mvn clean -Ptest package -DskipTests=true -Dmaven.javadoc.skip=true

  # docker镜像推送
#  - name: docker
#    image: plugins/docker
#    settings:
#      username:
#        from_secret: docker_user
#      password:
#        from_secret: docker_pwd
#      mirror: https://wm9kcxms.mirror.aliyuncs.com
#      repo: registry.cn-hangzhou.aliyuncs.com/hbhb/drone-ci
#      registry: registry.cn-hangzhou.aliyuncs.com
#      tags: latest
#      dockerfile: ./Dockerfile

  # ssh远程执行脚本
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 112.13.201.108
      port: 2022
      username: root
      password: Qaz2@wsx
#      key:
#        from_secret: ssh_key
      command_timeout: 3m
      script_stop: false
      script:
        - docker-compose ps

  # 钉钉通知
  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: dingtalk_token
      type: markdown
      tpl:
        [TPL_REPO_FULL_NAME] build [TPL_BUILD_STATUS], takes [TPL_BUILD_CONSUMING]s
        [TPL_COMMIT_MSG]
        [TPL_COMMIT_SHA]([TPL_COMMIT_LINK])
#        [[TPL_AUTHOR_NAME]([TPL_AUTHOR_EMAIL])](mailto:[TPL_AUTHOR_EMAIL])
        [Click To The Build Detail Page [TPL_STATUS_EMOTICON)]]([TPL_BUILD_LINK])
      message_color: true
      success_color: 008000
      failure_color: FF0000
      message_pic: true
      sha_link: true
    when:
      status: [failure, success]

volumes:
  - name: maven_local_repo
    host:
      path: /app/data/maven_local_repo


