kind: pipeline
type: docker
name: default

steps:
  # maven打包
  - name: build
    image: maven:3-jdk-8
    volumes:
      # 设置maven缓存
      - name: maven_local_repo
        path: /root/.m2
    commands:
      - mvn clean -Pprd package -DskipTests=true -Dmaven.javadoc.skip=true

  # docker镜像推送
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pwd
      mirror: https://wm9kcxms.mirror.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/drone-ci
      registry: registry.cn-hangzhou.aliyuncs.com
      tags: latest
      dockerfile: ./Dockerfile

  # ssh远程执行脚本
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      port: 22
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      command_timeout: 3m
      script_stop: false
      script:
        - docker-compose stop drone-ci
        - cd ~ & ll
        - docker-compose rm -f drone-ci
        - docker rmi registry.cn-hangzhou.aliyuncs.com/drone-ci
        - docker-compose up -d drone-ci

  # 钉钉通知
  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: dingtalk_token
      type: markdown
      tpl: ./markdown.tpl
      tips_title: 新的构建已完成，请测试
      message_color: true
      success_color: 39D839
      failure_color: E93939
      tpl_build_status_success: 成功
      tpl_buaild_status_failure: 失败
      message_pic: true
      sha_link: true
    when:
      status: [failure, success]

volumes:
  # 挂载在宿主机的maven缓存目录
  - name: maven_local_repo
    host:
      path: /data/maven
